language: node_js
node_js:
  - 8.12.0

env:
  global:
    - BUILD_TIMEOUT=10000

install:
  - npm install codecov --save-dev

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

branches:
  only:
    - master
