version: 2
jobs:
  build:
    working_directory: ~/react-tabllist
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: npm install -g npm@latest
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: npm install -g yarn
      - run:
          name: install-package
          command: yarn
      - run:
          name: test-stylelint
          command: yarn lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: yarn test
