version: 2
jobs:
  build:
    working_directory: ~/react-tabllist
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: sudo npm install -g yarn
      - run:
          name: install-package
          command: sudo yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test-stylelint
          command: sudo yarn lint
      - run:
          name: run-unit-test-and-uploading-reports
          command: sudo yarn test
